config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :resumes, only: [:destroy, :create]
  resources :positions, except: [:show]
  resources :schedules, except: [:edit, :update]
  resources :personnels do
  	member do
  		get 'choose_position'
      get 'choose_schedule', to: 'schedules#choose_schedule'
      get 'position_schedule', to: 'schedules#position_schedule'
      post 'choose_position_sch', to: 'schedules#choose_position_sch'
  	end
  	collection do
  		post 'add_position'
  	end
  end

  root 'personnels#index'
end

app/models/position.rb
class Position < ApplicationRecord
	validates :name, presence: true
	has_and_belongs_to_many :personnels
	has_many :resume, dependent: :destroy

	after_validation do	
		self.name = name.titleize
	end
	# def self.show_pos(personnel)
	# 	return personnel.positions.map{|p| [p.name, p.id]}
	# end

	def self.lead_position
		l = Position.where("name LIKE '%lead%'").map(&:id)
		return l[0]
	end

	def self.singer_position
		l = Position.lead_position
		s = Position.where("name LIKE '%singer%' and id != #{l}").map(&:id)
		return s[0]
	end

	def self.any_singer(id, sch)
		scheObj = Schedule.new
		position = scheObj.position_able(id, sch)
		singer = Position.singer_position
		pos_new = position << singer
		return Position.where(id: pos_new)
	end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
	before_action :set_position, only: [:edit, :update, :destroy]	
	before_action :authenticate_user!

	def index
		@positions = Position.paginate(:page => params[:page], :per_page => 5)
	end

	def new
		@position = Position.new
	end

	def create
		# render plain: params[:position].inspect
		@position = Position.new(position_params)
		if @position.save
			redirect_to positions_url, notice: 'Sukses buat Position'
		else
			render :new, notice: 'Gagal buat Position'
		end
	end

	def edit
	end

	def update
		if @position.update(position_params)
			redirect_to positions_url, notice: 'Sukses update Position'
		else
			render :edit, notice: 'Gagal update Position'
		end
	end

	def destroy
		@position.destroy
		redirect_to positions_url, notice: 'Sukses hapus Position'
	end

	private
	def position_params
		params.require(:position).permit(:name)
	end
	def set_position
		@position = Position.find(params[:id])
	end
end

app/views/positions/edit.html.erb
<% if @position.errors.any? %>
	<div class="alert alert-danger">
    	<h2>Terdapat <%= @position.errors.size %> error</h2>
    	Field Name <%= @position.errors[:name][0] %>
	</div>
<% end %>
<%= form_for :position, url: position_path(@position), method: :put do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.submit %>
<%end%>

app/views/positions/index.html.erb
<strong><%=notice%></strong>
<table class="table table-bordered">
	<tr>
		<th width="50px">No.</th>
		<th>Nama Posisi</th>
		<th>Aksi</th>
	</tr>
	<% @positions.each_with_index do |p, i| %>
	<tr>
		<td><%= i+1 %></td>
		<td><%= p.name %></td>
		<td><%= link_to 'Edit', edit_position_path(p) %> | <%= link_to 'Hapus', position_path(p), method: :delete, data: {confirm: 'Yakin?'} %></td>
	</tr>
	<%end%>
</table>
<%= link_to '+New Position', new_position_path %>

app/views/positions/new.html.erb
<% if @position.errors.any? %>
	<div class="alert alert-danger">
    	<h2>Terdapat <%= @position.errors.size %> error</h2>
    	Field Name <%= @position.errors[:name][0] %>
	</div>
<% end %>
<%# i = 0 %>
<%= form_for :position, url: positions_path, method: :post do |f| %>
	<%# while i < 5 do %>
	<!-- form_for(@post, data: { behavior: "autosave" }, html: { name: "go" }) -->
		<%= f.label :name%>
		<%= f.text_field :name%><br>
		<%# i+=1 %>
	<%#end%>
	<%= f.submit %>
<%end%>