config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :resumes, only: [:destroy, :create]
  resources :positions, except: [:show]
  resources :schedules, except: [:edit, :update]
  resources :personnels do
  	member do
  		get 'choose_position'
      get 'choose_schedule', to: 'schedules#choose_schedule'
      get 'position_schedule', to: 'schedules#position_schedule'
      post 'choose_position_sch', to: 'schedules#choose_position_sch'
  	end
  	collection do
  		post 'add_position'
  	end
  end

  root 'personnels#index'
end

app/models/schedule.rb
class Schedule < ApplicationRecord
	FORMAT = [
		[1, 2, 3, 4, 5, 6, 6, 6],
		[2, 3, 4, 5, 6, 6, 6],
		[1, 2, 4, 5, 6, 6, 6],
		[1, 4, 5, 6, 6, 6]
	]

	validates :perform_date, uniqueness: true
	has_many :resume, dependent: :destroy

	# def self.jumlah_posisi(id)
	# 	personnel = Personnel.find(id)
	# 	return personnel.positions.count
	# end

	def self.checking_formation(format=[])
		format = format.kind_of?(Array) ? format.sort : []

		return 'Band siap manggung' if [0,1,2].include?(FORMAT.index(format))
		return 'Band siap manggung, tapi anda yakin tidak akan menambahkan drummer?' if FORMAT.index(format) == 3
		return 'Posisi kosong' if format == []
		'Posisi belum terisi sempurna'
	end

	def empt_array(id, sch)
		personnel = Personnel.find(id)
		array = Schedule.per_array(personnel)
		cek = Schedule.sche_array(sch, array)
	end

	def self.schedule_not(id)
		resume = Resume.where(personnel_id: id).map(&:schedule_id)
		return Schedule.where.not(id: resume).order(perform_date: :asc)
	end

	def self.res_position(id)
		Resume.joins(:personnel, :position, :schedule).where(schedule_id: id)
	end

	def self.schedule_format(schedule)
		format = Resume.order(position_id: :asc).where(schedule_id: schedule).map(&:position_id)
		checking_formation(format)
		

		# elsif FORMAT.index(format) == 3
		# 	'Band siap manggung, tapi anda yakin tidak akan menambahkan drummer?'
		# elsif format == []
		# 	'Posisi kosong'
		# else
		# 	'Posisi belum terisi sempurna'
		# end
	end

	def position_open(id, sch)
		personnel = Personnel.find(id)
		array = Schedule.per_array(personnel)
		cek = Schedule.sche_array(sch, array)
		array_cek = array - cek
		return Position.where(id: array_cek)
	end

	def self.singer_pos(id, sch)
		return Position.where(id: 6)
	end


	def position_able(id, sch)
		personnel = Personnel.find(id)
		array = Schedule.per_array(personnel)
		cek = Schedule.sche_array(sch, array)
		array_cek = array - cek
		if array_cek == [] #kembalikan array position_id personnel jika hasil kurang jadi array kosong
			return array
		else
			return array_cek
		end
	end

	def self.sche_array(sch, array)
		Resume.where(schedule_id: sch, position_id: array).map(&:position_id)
	end

	def self.per_array(personnel)
		personnel.positions.map(&:id)
	end

	def self.take_position(position, personel, sch, id)
		if position.include? personel || position == [personel] #kalau posisi berisi id singer
			if Resume.pos_sche(personel, sch).count < 3 #cek singer udah tiga?
				[Schedule.singer_pos(id, sch), nil, nil] 
			else
				[nil, 'Posisi Singer sudah terisi penuh.', "choose_schedule_personnel_url(params[:id])"]
			end
		else
			[nil, 'Posisi sudah penuh', "personnel_path(params[:id])"]
		end
	end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
	before_action :authenticate_user!
	before_action :creat_automatically

	def index
		@schedules = Schedule.all.paginate(:page => params[:page], :per_page => 5)
		
	end

	def upcoming
		@schedules = Schedule.list_schedule('>').paginate(:page => params[:page], :per_page => 5)		
	end


	def export_excel
		@schedulez, @note = Schedule.export_schedule(params[:range], params[:note])

		@positions = Position.all
		respond_to do |format|
			format.html
			format.xlsx
			format.pdf {render template: 'schedules/pdf', pdf: 'file'}
		end		
	end

	def export_pdf
		@schedules = Schedule.all
		respond_to do |format|
	      format.html
	      format.pdf do
      	  pdf = ExportPdf.new(@schedules, 'ada')
	        send_data pdf.render,
	          filename: "export.pdf",
	          type: 'application/pdf',
	          disposition: 'inline'
	      end
	    end
	end

	def history
		@schedules = Schedule.list_schedule('<')
	end

	def show
		@schedule = Schedule.find(params[:id])
	end

	def new
		@schedule = Schedule.new
	end

	def create
		# render plain: params[:schedule].inspect
		@schedule = Schedule.new(schedule_params)
		if @schedule.save
			redirect_to schedules_url, notice: 'Penyimpanan posisi berhasil'
		else
			render :new
		end
	end

	def choose_schedule
		@schedules = Schedule.all.order(perform_date: :asc)
	end

	def choose_position_sch
		sch = params[:resume][:schedule_id]
		id = params[:id]
		singer = Position.personnel_position
		position = Position.position_able(id, sch)

		personnel = Personnel.find(id)
		position_personnel = Position.per_array(personnel)#poisinya apa aja
		if position_personnel.length == 1
			if Resume.position_cek(position_personnel,sch)
				redirect_to personnel_url(id, schedule_id: sch), notice: 'penuh'
			else
				p = position[0]
				save_instant(sch, id, p)
			end
		else
			if position_personnel.include? singer
				position_singer(position, singer, sch)
			else
				if Position.position_open(id, sch) == []
					redirect_to personnel_url(id, schedule_id: sch), notice: 'penuh'
				else
					redirect_to personnel_url(id, schedule_id: sch)
				end
			end
		end


		# if Resume.position_cek(position,sch)#posisi terisi
		# 	if position.length > 1#posisi lebih dari satu
		# 		if scheObj.empt_array(id, sch) == [] #cek posisi setalh di kurang yg tersedia kosong
		# 			position_singer(position, singer, sch)
		# 		else
		# 			@personnel  = Position.position_open(id, sch)
		# 		end
		# 	else#posisi cuma satu
		# 		position_singer(position, singer, sch)
		# 	end
		# else#posisi belum terisi
		# 	if position.length == 1#posisi cuma satu
		# 		if Resume.pos_sche(singer, sch).count < 3 #cek singer udah tiga?
		# 			@personnel  = Position.any_singer(id, sch)
		# 		else
		# 			p = position[0]
		# 			save_instant(sch, id, p)
		# 		end
		# 	else
		# 		@personnel  = Position.position_open(id, sch)
		# 	end
		# end
	end

	def creat_automatically
		date = Date.today
		plus = date + 14
		if plus.saturday?
			Schedule.create(perform_date: plus) if Schedule.find_by(perform_date: date).blank?
		end
	end

	private

	def position_singer(position, singer, sch)
		@personnel, notice, url = Position.take_position(position, singer, sch, params[:id])

		redirect_to eval(url), notice: notice  if @personnel.nil?
	end

	def save_instant(sch, id, p)
		@resume = Resume.new(schedule_id: sch, personnel_id: id , position_id: p)
		if @resume.save
			redirect_to personnel_url(id, schedule_id: sch), notice: 'Penyimpanan posisi berhasil'
		else
			@schedules = Schedule.order(perform_date: :asc)
			redirect_to personnel_url(id) , notice: 'Penyimpanan posisi gagal'
		end
	end

	def schedule_params
		params.require(:schedule).permit(:perform_date)
	end

end

app/helpers/schedule_helper.rb
module ScheduleHelper
	def self.range
		now = Date.today()
		akhir = Date.new(2017,12,31) 
		date = (now.at_beginning_of_month..akhir.at_end_of_month)
	end
end

app/views/schedules/_form_date_range.html.erb
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <style>
    label, input { display:block; }
    input.text { margin-bottom:12px; width:95%; padding: .4em; }
    fieldset { padding:0; border:0; margin-top:25px; }
    h1 { font-size: 1.2em; margin: .6em 0; }
    div#users-contain { width: 350px; margin: 20px 0; }
    div#users-contain table { margin: 1em 0; border-collapse: collapse; width: 100%; }
    div#users-contain table td, div#users-contain table th { border: 1px solid #eee; padding: .6em 10px; text-align: left; }
    .ui-dialog .ui-state-error { padding: .3em; }
    .validateTips { border: 1px solid transparent; padding: 0.3em; }
  </style>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    var dialog, form,
 
      // From http://www.whatwg.org/specs/web-apps/current-work/multipage/states-of-the-type-attribute.html#e-mail-state-%28type=email%29
      note = $( "#note" ),
      allFields = $( [] ).add( note );
  
    function saveNote() {
      var valid = true;
      allFields.removeClass( "ui-state-error" );

      if ( valid ) {
        $("#position").submit();
        dialog.dialog( "close" );
      }
      return valid;
    }
 
    dialog = $( "#dialog-form" ).dialog({
      autoOpen: false,
      height: 400,
      width: 350,
      modal: true,
      buttons: {
        "Save Note": saveNote,
        Cancel: function() {
          dialog.dialog( "close" );
        }
      },
      close: function() {
      }
    });
 
    $( "#print" ).button().on( "click", function() {
      dialog.dialog( "open" );
    });
  } );
  </script>
  <script>
  $( function() {
    var dateFormat = "yy-mm-dd",

      //TAMBAHAN AGAR CLIKC BISA TWICE
      // var b1 = $("#print-excel");
      // b1.click(function(){
      //     console.log('clicked', this.id)
      // })
      //TAMBAHAN AGAR CLIKC BISA TWICE

      from = $( "#from" )
        .datepicker({
          defaultDate: "+1w",
          changeMonth: true,
          numberOfMonths: 3,
          dateFormat: "yy-mm-dd"
        })
        .on( "change", function() {
          to.datepicker( "option", "minDate", getDate( this ) );
        }),
      to = $( "#to" ).datepicker({
        defaultDate: "+1w",
        changeMonth: true,
        numberOfMonths: 3,
        dateFormat: "yy-mm-dd"
      })
      .on( "change", function() {
        from.datepicker( "option", "maxDate", getDate( this ) );
      });
 
    function getDate( element ) {
      var date;
      try {
        date = $.datepicker.parseDate( dateFormat, element.value );
      } catch( error ) {
        date = null;
      }
 
      return date;
    }
  } );
  </script>
</head>

<div id="dialog-form" title="Create note">
  <%= form_for :range, url: export_excel_schedules_path(format: :xlsx), html: {id: 'position', name: 'position'} do |f| %>
    <div class="form-group">
      <%= f.label :note %>
      <%= f.text_area :note, {class: 'form-control'}%><br>
    </div>
    <div class="form-group">
      <%= f.label :from , value: 'Tanggal' %>
      <%= f.text_field :from, {id: "from", placeholder: 'From', class: 'form-control'} %>
      <%= f.text_field :to, {id: "to", placeholder: 'To', class: 'form-control'} %>
    </div>
  <%end%>
</div>

<h2>Print Excel Report</h2>
<button id="print">Download Excel</button>
<br>

app/views/schedules/_form_dialog.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Dialog - Modal form</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <style>
    label, input { display:block; }
    input.text { margin-bottom:12px; width:95%; padding: .4em; }
    fieldset { padding:0; border:0; margin-top:25px; }
    h1 { font-size: 1.2em; margin: .6em 0; }
    div#users-contain { width: 350px; margin: 20px 0; }
    div#users-contain table { margin: 1em 0; border-collapse: collapse; width: 100%; }
    div#users-contain table td, div#users-contain table th { border: 1px solid #eee; padding: .6em 10px; text-align: left; }
    .ui-dialog .ui-state-error { padding: .3em; }
    .validateTips { border: 1px solid transparent; padding: 0.3em; }
  </style>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    var dialog, form,
 
      // From http://www.whatwg.org/specs/web-apps/current-work/multipage/states-of-the-type-attribute.html#e-mail-state-%28type=email%29
      note = $( "#name" ),
      allFields = $( [] ).add( note );
  
    function saveNote() {
      var valid = true;
      allFields.removeClass( "ui-state-error" );

      if ( valid ) {
        $("#position").submit();
        dialog.dialog( "close" );
      }
      return valid;
    }
 
    dialog = $( "#dialog-form" ).dialog({
      autoOpen: false,
      height: 300,
      width: 350,
      modal: true,
      buttons: {
        "Save Note": saveNote,
        Cancel: function() {
          dialog.dialog( "close" );
        }
      },
      close: function() {
      }
    });
 
    $( "#print" ).button().on( "click", function() {
      dialog.dialog( "open" );
    });
  } );
  </script>
</head>
<body>
 
<div id="dialog-form" title="Create note">
 	<%= form_for :note, url: export_excel_schedules_path(format: :xlsx), html: {id: 'position', name: 'position'} do |f| %>
		<%= f.label :name %>
		<%= f.text_area :name%><br>
	<%end%>
</div>
<button id="print">Download Excel</button>

app/views/schedules/_table.html.erb
<tr>
	<td>
		<%= s.perform_date %>
	</td>
	<td>
		<%= s.checking_formation %>
	</td>
	<td>
		<% s.res_position.each do |p| %>
			<%= p.personnel.name %> | <%= p.position.name %>
			<% if current_user.role == 0 %>
				<%= link_to 'hapus', resume_path(p), method: :delete, data: {confirm: 'Yakin?'} %>
			<%end%>
			<br>
		<%end%>
	</td>
</tr>

app/views/schedules/choose_position_sch.html.erb
<%=notice%><br>
<%= form_for :resume, url: resumes_path, method: :post do |f| %>
	<%= f.hidden_field :schedule_id, {value: params[:resume][:schedule_id]} %>
	<%= f.hidden_field :personnel_id, {value: params[:id]} %>
	<%= f.label :position_id %>
	<%= select("resume", "position_id", @personnel.map{|p| [p.name, p.id]}) %>
	<%= f.submit %>
<%end%>

app/views/schedules/choose_schedule.html.erb
<%=notice%><br>
<%= form_for :resume, url: choose_position_sch_personnel_path(params[:id]), method: :post do |f| %>
	<%= f.hidden_field :personnel_id, {value: params[:id]} %>
	<%= f.label :schedule_id %>
	<%= select("resume", "schedule_id", @schedules.collect{|p| [p.perform_date, p.id]}) %>
	<%= f.submit %>
<%end%>

app/views/schedules/history.html.erb
<table class="table table-bordered">
	<tr>
		<th>Tanggal</th>
		<th>Keterangn</th>
		<th>Personnel | Posisi</th>
	</tr>
	<%= render partial: 'table', collection: @schedules, as: :s, locals: {message: 'Band sudah manggung'} %>
</table>
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<%= render partial: 'form_dialog'%> | 
<%= link_to 'Download PDF', export_pdf_schedules_path(format: :pdf) %> | 
<%= link_to '+New Schedule', new_schedule_path %> | <%= link_to 'History', history_schedules_path %>
<hr>
<table class="table table-bordered">
	<tr>
		<th>Tanggal</th>
		<th>Keterangn</th>
		<th>Personnel | Posisi</th>
	</tr>
	<%= render partial: 'table', collection: @schedules, as: :s, locals: {message: ''}%>
</table>

<%= will_paginate @schedules %><br>
 <!--  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<body>
<label for="from">From</label>
<input type="text" id="from" name="from">
<label for="to">to</label>
<input type="text" id="to" name="to"> 
-->

app/views/schedules/new.html.erb
<% if @schedule.errors.any? %>
	<div class="alert alert-danger">
		<h2>Terdapat <%= @schedule.errors.size %> error</h2>
		<% @schedule.errors.full_messages.each do |e| %>
			<%= e %>
		<%end%>
	</div>
<%end%>
<%= form_for :schedule, url: schedules_path, method: :post do |f| %>
	<%= f.label :perform_date %>
	<%= select("schedule", "perform_date", @schedule.range.select{|p| [p]} ) %>
	<%= f.submit %>
<%end%>

app/views/schedules/position_schedule.html.erb
<%=notice%>

app/views/schedules/upcoming.html.erb
<h2>Upcoming Schedule</h2><br>
<%= link_to 'Download as .pdf', export_pdf_schedules_path(format: :pdf) %> | 
<%= link_to '+New Schedule', new_schedule_path %> | <%= link_to 'History', history_schedules_path %>
<hr>
<table class="table table-bordered">
	<tr>
		<th>Tanggal</th>
		<th>Keterangn</th>
		<th>Personnel | Posisi</th>
	</tr>
	<%= render partial: 'table', collection: @schedules, as: :s, locals: {message: ''}%>
</table>
<%= will_paginate @schedules %>
<hr>
<%= render partial: 'form_date_range'%>
<br>