config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :resumes, only: [:destroy, :create]
  resources :positions, except: [:show]
  resources :schedules, except: [:edit, :update]
  resources :personnels do
  	member do
  		get 'choose_position'
      get 'choose_schedule', to: 'schedules#choose_schedule'
      get 'position_schedule', to: 'schedules#position_schedule'
      post 'choose_position_sch', to: 'schedules#choose_position_sch'
  	end
  	collection do
  		post 'add_position'
  	end
  end

  root 'personnels#index'
end

app/models/personnel.rb
class Personnel < ApplicationRecord
	validates :name, presence: true
	has_and_belongs_to_many :positions
	has_many :resume, dependent: :destroy

	after_validation do	
		self.name = name.titleize
	end

	def self.hitung_posisi(personnel)
		Personnel.find(personnel).positions.count
	end
end

app/controllers/personnels_controller.rb
class PersonnelsController < ApplicationController
	before_action :set_personnel, only: [:show, :edit, :update, :destroy, :choose_position]
	before_action :authenticate_user!
	
	def index
		@personnels = Personnel.paginate(:page => params[:page], :per_page => 5)
	end

	def show
		@schedules = Schedule.where(id: params[:schedule_id])
		@position = @personnel.show_position
		@res_schedule = Resume.next_schedule(params[:id])
		@schedule_able = Schedule.schedule_not(params[:id])
		@position_open = Position.post_choose(params[:id], params[:schedule_id])
	end

	def new
		@personnel = Personnel.new
	end

	def create
		# render plain: params[:personnel].inspect
		@personnel = Personnel.new(personnel_params)
		if @personnel.save
			redirect_to @personnel, notice: 'Sukses buat Personnel'
		else
			render :new, notice: 'Gagal buat Personnel'
		end
	end

	def edit
	end

	def update
		if @personnel.update(personnel_params)
			redirect_to @personnel, notice: 'Sukses update Personnel'
		else
			render :edit, notice: 'Gagal buat Personnel'
		end
	end

	def destroy
		@personnel.destroy
		redirect_to personnels_path, notice: 'Sukses hapus Personnel'
	end

	def choose_position
		@positions = Position.all		
	end

	def add_position
		# render plain: params[:c_pos].inspect

		@position = Position.find(params[:c_pos][:position_id])
		@personnel = Personnel.find(params[:c_pos][:personnel_id])

		@personnel.positions << @position
		redirect_to personnels_path
	end

	def create_account
		@user = User.new
	end

	def save_account
		# render plain: params[:user].inspect
		@user = User.new(create_account_params)
		if @user.save
			redirect_to personnels_url, notice: 'Succesfully create a new account.'
		else
			error =  @user.errors.full_messages
			render :create_account
		end
	end

	private
	def personnel_params
		params.require(:personnel).permit(:name)
	end

	def set_personnel
		@personnel = Personnel.find(params[:id])
	end

	def create_account_params
		params.require(:user).permit(:role, :email, :password, :password_confirmation, :personnel_id)
	end
end

app/views/personnels/_list_personnel.html.erb
<tr>
	<td><%= link_to p.name, personnel_path(p) %><%= '*' if p.hitung_posisi > 1 %></td>
	<td><%= link_to 'Edit', edit_personnel_path(p)%> | <%= link_to 'Hapus', personnel_path(p), method: :delete,data: {confirm: 'Yakin?'} %> | <%= link_to 'Tambah Posisi', choose_position_personnel_path(p.id) %> | <%= link_to 'Buat Akun', create_account_personnel_path(p.id) if p.check_account.blank? %></td>
</tr>

app/views/personnels/choose_position.html.erb
<%= form_for :c_pos, url: add_position_personnels_path do |f| %>
<table class="table table-stripped table-bordered">
<tr>
	<th>Personnel</th>
	<td>: <%= @personnel.name %></td>
</tr><tr>
	<%= f.hidden_field :personnel_id, {value: params[:id] } %>
	<th><%= f.label :position_id %></th>
	<td>: <%= select("c_pos", "position_id", @personnel.add_position.collect {|p| [ p.name, p.id ] }) %></td>
</tr><tr>
	<td><%= f.submit 'Simpan' %></td>
</tr>
<% end %>
</table>

app/views/personnels/create_account.html.erb
<% if @user.errors.any? %>
	<div class="alert alert-danger">
		<h2>Terdapat <%= @user.errors.size %> error</h2>
		<% @user.errors.full_messages.each do |e| %>
			<%= e %><br>
		<%end%>
	</div>
<%end%>
<h2>Create Account</h2>
<%= render partial: "users/registrations/form", locals:{resource: @user, url: save_account_personnels_path} %>

app/views/personnels/edit.html.erb
 <% if @personnel.errors.any? %>
	<div class="alert alert-danger">
	    <h2>Terdapat <%= @personnel.errors.size %> error</h2>
	      Field Name <%= @personnel.errors[:name][0] %>
	</div>
<% end %>
<%= form_for :personnel, url: personnel_path(@personnel), method: :put do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.submit %>
<%end%>

app/views/personnels/index.html.erb
<table class="table table-bordered">
	<tr>
		<th>Nama Personel</th>
		<th>Aksi</th>
	</tr>
	<%= render partial: 'list_personnel', collection: @personnels, as: :p %>
</table>
<%= will_paginate @personnels %>
* <i>Personnel dengan berbagai posisi, utamakan personnel yang hanya memiliki 1 posisi untuk di masukkan ke jadwal.</i></br>
<%= link_to '+New Personil', new_personnel_path %>

app/views/personnels/new.html.erb
<% if @personnel.errors.any? %>
	<div class="alert alert-danger">
    <h2>Terdapat <%= @personnel.errors.size %> error</h2>
      Field Name <%= @personnel.errors[:name][0] %>
	</div>
<% end %>
<%= form_for :personnel, url: personnels_path, method: :post do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.submit %>
<%end%>

app/views/personnels/show.html.erb
<head>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <style>
  .toggler { width: 500px; height: 200px; }
  #button { padding: .5em 1em; text-decoration: none; }
  #effect { width: 240px; height: 170px; padding: 0.4em; position: relative; }
  #effect h3 { margin: 0; padding: 0.4em; text-align: center; }
  </style>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    // run the currently selected effect
    function runEffect() {
      var options = {};
 
      // Run the effect
      $( "#effect" ).show( "blind", options, 500);
    };
 
    //callback function to bring a hidden box back
    function callback() {
      setTimeout(function() {
        $( "#effect:visible" ).removeAttr( "style" ).fadeOut();
      }, 1000 );
    };
 
    // Set effect from select menu value
    $( "#button" ).on( "click", function() {
      runEffect();
    });
 
    $( "#effect" ).hide();
  } );

  </script>
</head>
<h2>Resume Personnel</h2>
<table class="table table-bordered">
	<tr>
		<th>Name :</th>
		<td><%= @personnel.name %><br><%= link_to 'Edit Personnel', edit_personnel_path(params[:id]) %></td>
	</tr>
	<tr>
		<th>Position :</th>
		<td>
			<% @position.each_with_index do |p, i| %>
			<%= i+1 %>. <%= p %><br>
			<%end%>
		</td>
	</tr>
	<tr>
		<th>Jadwal :</th>
		<td>
			<% @res_schedule.each_with_index do |p, i| %>
				<%= i+1 %>. 
				<%= (p.schedule.perform_date).strftime('%d %B %Y') %> | 
				<%= p.position.name %> | 
				<%=link_to 'Hapus', resume_path(p), method: :delete, data: {confirm: 'Yakin?'} %></br>
			<%end%>
			<%= link_to 'History', history_schedules_path %>
		</td>
	</tr>
	<tr>
		<th>Email :</th>
		<td> <%= @personnel.email %></td>
	</tr>
</table>
<hr>
<h2>Input Jadwal</h2>
<%= form_for :resume do |f| %>
	<%= f.hidden_field :personnel_id, {value: params[:id]} %>
	<% if @schedule_able.any? %>
		<strong>Tanggal: </strong>
		<%= select("resume", "schedule_id", @schedule_able.collect{|p| [p.perform_date, p.id]}) %>
		<%= f.submit 'Choose', :html => {:id => "button"}%>
	<% else %>
		Jadwal sudah terisi semua
	<% end %>
<%end%>
<% if notice %>
<table class="table table-bordered table-striped">
	<tr>
		<th>Tanggal</th>
		<th>Keterangn</th>
		<th>Personnel | Posisi</th>
	</tr>
	<% @schedules.each do |s| %>
		<tr>
			<td>
				<%= (s.perform_date).strftime('%d-%m-%Y') %>
			</td>
			<td>
				<%= s.checking_formation %>
			</td>
			<td>
				<% s.res_position.each_with_index do |p, i| %>
					<%= i+1 %>. 
					<%= p.personnel.name %> | 
					<%= p.position.name %> | 
					<%= link_to 'Hapus', resume_path(p), method: :delete, data: {confirm: 'Yakin?'} %><br>
				<%end%>
			</td>
		</tr>
	<%end%>
</table>
<%end%>
<% if params[:schedule_id] && notice.blank? %>
<table class="table table-bordered table-striped">
	<tr>
		<th>Tanggal</th>
		<th>Keterangn</th>
		<th>Personnel | Posisi (Please choose position)</th>
	</tr>
	<% @schedules.each do |s| %>
		<tr>
			<td>
				<%= (s.perform_date).strftime('%d-%m-%Y') %>
			</td>
			<td>
				<%= s.checking_formation %>
			</td>
			<td>
				<% @position_open.each do |p| %>
					<%= form_for :resume, url: resumes_path do |f| %>
					<%= f.hidden_field :schedule_id, {value: params[:schedule_id] } %>
					<%= f.hidden_field :position_id, {value: p[0] } %>
					<%= f.hidden_field :personnel_id, {value: params[:id] } %><br>
					<%= @personnel.name %> | 
						<%= link_to p[1], personnels_path %>
						<%= f.submit 'Select' %><br>
					<%end%>
				<%end%>
			</td>
		</tr>
	<%end%>
</table>
<%end%>
 
<button id="button" class="ui-state-default ui-corner-all">Run Effect</button>

<div class="toggler">
  <div id="effect" class="ui-widget-content ui-corner-all">
    <h3 class="ui-widget-header ui-corner-all">Show</h3>
    <p>
      Etiam libero neque, luctus a, eleifend nec, semper at, lorem. Sed pede. Nulla lorem metus, adipiscing ut, luctus sed, hendrerit vitae, mi.
    </p>
  </div>
</div>