config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :resumes, only: [:destroy, :create]
  resources :positions, except: [:show]
  resources :schedules, except: [:edit, :update]
  resources :personnels do
  	member do
  		get 'choose_position'
      get 'choose_schedule', to: 'schedules#choose_schedule'
      get 'position_schedule', to: 'schedules#position_schedule'
      post 'choose_position_sch', to: 'schedules#choose_position_sch'
  	end
  	collection do
  		post 'add_position'
  	end
  end

  root 'personnels#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ceband</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %> <!-- link untuk ngambil bootstrap online-->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="alert alert-success">
    <%if user_signed_in?%>
      <%= link_to 'Personil', personnels_path %> | 
      <%= link_to 'Position', positions_path %> | 
      <%= link_to 'Jadwal', schedules_path %> || 
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <%else%>
      <%= link_to 'Sign Up', new_user_registration_path %> | 
      <%= link_to 'Login', new_user_session_path %>
    <%end%>
    </div>

    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>